### ISSUE TITLE
[ ❗ Enhancement] Repository Improvements

### ISSUE THREAD

**Issue by EdricChan03** [EdricChan03/StudyBuddy-web#436]
It's about time to actually improve this repository.

# TODO list

## Maintainer improvements

- [ ] Add issue templates
  - [ ] Bug reports
  - [ ] Feature requests/enhancements
  - [ ] UX/UI requests/enhancements
  - [ ] Other templates (if necessary)
- [ ] Add contributing guide
  - [ ] Expected commit/contributing standards
  - [ ] Indicate how to run the app locally
- [ ] Handle issues/PRs from first-time users

## Continuous Integration

- [ ] Add initial GitHub Actions
  - [ ] Unit testing
  - [ ] Deploy to Firebase
  - [ ] Stale issues/PRs
  - [ ] Code scanning

## Other

- [ ] Improve repository transparency
  - [ ] Add updates document to the wiki/repository
  - [ ] Add initial help guides
